spring:
  application:
    name: diagnosis-service
    
    
management:
  endpoints:
    web:
      exposure:
        include:
        - info
        - refresh
        
info:
  app:
    name: diagnosis service
    description: This service handles all diagnosis information
    version: 1.0
    java:
      version: 1.9
    spring:
      cloud:
        version: Hoxton.SR6