spring:
  application:
    name: doctor-service
    
management:
  endpoints:
    web:
      exposure:
        include:
        - info
        - refresh
        
        
info:
  app:
    name: doctor service
    description: This service handles all doctor doctor information
    version: 1.0
    java:
      version: 1.9
    spring:
      cloud:
        version: Hoxton.SR6